from __future__ import annotations

import json
from pathlib import Path
from textwrap import dedent
from typing import Iterable


class LocalLLM:
    """Deterministic local helper that simulates planning and code generation.

    This class intentionally avoids network calls so the demo remains runnable.
    """

    def create_plan(self, request: str) -> list[str]:
        normalized = request.strip()
        if not normalized:
            return []

        keywords = [
            "read the request and identify the required project files",
            "generate or update the implementation for the requested feature",
            "review the generated patch before applying it",
            "validate the updated project and capture any errors",
        ]
        return [f"{index + 1}. {step}" for index, step in enumerate(keywords)]

    def build_patch(self, request: str, task: str, workspace: Path) -> str:
        summary = self._request_summary(request)
        target = workspace / "generated_task.py"
        content = dedent(
            f'''
            """Generated by mini-Codex for task: {task}"""

            REQUEST_SUMMARY = {summary!r}
            TASK = {task!r}


            def run() -> str:
                return f"Task complete: {{TASK}} | Request: {{REQUEST_SUMMARY}}"
            '''
        ).strip() + "\n"

        payload = {
            "edits": [
                {
                    "file": str(target.relative_to(workspace)),
                    "content": content,
                }
            ]
        }
        return json.dumps(payload, indent=2)

    def regenerate_patch(self, request: str, task: str, workspace: Path, error: str | None) -> str:
        suffix = f" Previous validation error: {error}" if error else ""
        return self.build_patch(f"{request}{suffix}", task, workspace)

    @staticmethod
    def _request_summary(request: str, max_words: int = 16) -> str:
        words = request.split()
        return " ".join(words[:max_words])


def format_task_list(tasks: Iterable[str]) -> str:
    return "\n".join(tasks)
